INSERT INTO public.person (first_name,last_name,email,company) VALUES
	 ('Ailsun','Soles','asoles2o@kickstarter.com','Wordify'),
	 ('Alexandre','Finicj','afinicji@istockphoto.com','JumpXS'),
	 ('Christoffer','Tremelling','ctremelling1g@storify.com','Zoonder'),
	 ('Andre','McCullagh','amccullagh1l@auda.org.au','Dynabox'),
	 ('Augusto','Mabbett','amabbett2a@tinypic.com','Skibox'),
	 ('Alex','Stean','asteans@trellian.com','Flipbug'),
	 ('Breno','Kersey','bkerseym@bravesites.com','Gigaclub'),
	 ('Bernardo','Soans','bsoansl@washingtonpost.com','Youopia'),
	 ('Barbara','Fowlds','bfowldsw@google.pl','Quaxo'),
	 ('Bianca','Tappington','btappington0@hc360.com','Brainsphere'),
	 ('Bryan','Etter','better1p@hugedomains.com','Centimia'),
	 ('Carlos','Causey','ccauseyz@ustream.tv','Blogspan'),
	 ('Carina','Hurrion','churrion12@studiopress.com','Twitterworks'),
	 ('Caio','Goulstone','zgoulstone9@google.com.hk','Divanoodle'),
	 ('Carol','Goundrill','cgoundrillh@themeforest.net','Aivee');